filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:

filebeat.modules:
- module: system
  syslog:
    enabled: true
    var.paths: 
      - /mnt/log/syslog*
  auth:
    enabled: true
    var.paths: 
      - /mnt/log/auth.log*

processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

xpack.monitoring.enabled: true

setup.kibana:
  host: "${KIBANA_HOSTS:kibana:5601}"
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
setup.dashboards.enabled: true
setup.dashboards.retry.enabled: true
setup.dashboards.retry.interval: 5s

http.enabled: true
http.host: filebeat
http.port: 5066
