heartbeat.monitors:
- type: icmp
  schedule: '@every 5s'
  name: es01
  hosts:
    - es01
- type: icmp
  schedule: '@every 5s'
  name: es02
  hosts:
    - es02
- type: icmp
  schedule: '@every 5s'
  name: kibana
  hosts:
    - kibana
- type: icmp
  schedule: '@every 5s'
  name: mysql
  hosts:
    - mysql
- type: icmp
  schedule: '@every 5s'
  name: java-backend
  hosts:
    - java-backend

- type: http
  schedule: '@every 5s'
  name: es01
  urls:
    - 'http://${ELASTICSEARCH_USERNAME:elastic}:${ELASTICSEARCH_PASSWORD:}@es01:9200'
- type: http
  schedule: '@every 5s'
  name: es02
  urls:
    - 'http://${ELASTICSEARCH_USERNAME:elastic}:${ELASTICSEARCH_PASSWORD:}@es02:9200'
- type: http
  schedule: '@every 5s'
  name: kibana
  urls:
    - 'http://kibana:5601'
- type: http
  schedule: '@every 10s'
  name: java-backend-jolokia
  urls:
    - 'http://java-backend:8778/jolokia/'
- type: http
  schedule: '@every 10s'
  name: java-backend-add-user
  urls:
    - 'http://java-backend:8080/demo/add?name=zyl&email=zyl@zyl.com'
  check.request:
    method: "GET"
  check.response:
    status: 200
    body:
      - Saved
      - saved
- type: http
  schedule: '@every 10s'
  name: java-backend-get-weather
  urls:
    - 'http://java-backend:8080/demo/weather?rflag=0'
  check.request:
    method: "GET"
  check.response:
    status: 200
    body:
      - currentCity

- type: tcp
  enabled: true
  schedule: '@every 5s'
  name: mysql
  hosts: ["tcp://mysql:3306"]

processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

xpack.monitoring.enabled: true

#setup.kibana:
#  host: "${KIBANA_HOSTS:kibana:5601}"
#  username: '${ELASTICSEARCH_USERNAME:}'
#  password: '${ELASTICSEARCH_PASSWORD:}'
#setup.dashboards.enabled: true
#setup.dashboards.retry.enabled: true
#setup.dashboards.retry.interval: 5s

http.enabled: true
http.host: heartbeat
http.port: 5066
