heartbeat.monitors:
- type: icmp
  schedule: '@every 5s'
  name: es01
  hosts:
    - es01
- type: icmp
  schedule: '@every 5s'
  name: es02
  hosts:
    - es02
- type: icmp
  schedule: '@every 5s'
  name: kibana
  hosts:
    - kibana

- type: http
  schedule: '@every 5s'
  name: es01
  urls:
    - 'http://${ELASTICSEARCH_USERNAME:elastic}:${ELASTICSEARCH_PASSWORD:}@es01:9200'
- type: http
  schedule: '@every 5s'
  name: es02
  urls:
    - 'http://${ELASTICSEARCH_USERNAME:elastic}:${ELASTICSEARCH_PASSWORD:}@es02:9200'
- type: http
  schedule: '@every 5s'
  name: kibana
  urls:
    - 'http://kibana:5601'

processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

xpack.monitoring.enabled: true

#setup.kibana:
#  host: "${KIBANA_HOSTS:kibana:5601}"
#  username: '${ELASTICSEARCH_USERNAME:}'
#  password: '${ELASTICSEARCH_PASSWORD:}'
#setup.dashboards.enabled: true
#setup.dashboards.retry.enabled: true
#setup.dashboards.retry.interval: 5s

http.enabled: true
http.host: heartbeat
http.port: 5066
